SELECT 
    B.AUTHOR_ID,
    COALESCE(A.AUTHOR_NAME, '작자 미상') AS AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM 
    BOOK B
INNER JOIN 
    BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID 
    AND BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
JOIN 
    AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY 
    B.AUTHOR_ID, B.CATEGORY
ORDER BY 
    B.AUTHOR_ID ASC, B.CATEGORY DESC;