WITH RENTAL_STATUS AS (
    SELECT DISTINCT CAR_ID,
           CASE 
               WHEN EXISTS (
                   SELECT 1
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                   WHERE CAR_ID = CRCRH.CAR_ID
                   AND '2022-10-16' BETWEEN START_DATE AND END_DATE
               ) THEN '대여중'
               ELSE '대여 가능'
           END AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
)
SELECT CAR_ID, AVAILABILITY
FROM RENTAL_STATUS
ORDER BY CAR_ID DESC;