WITH RECURSIVE Hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 
    FROM Hours 
    WHERE HOUR < 23
)
SELECT 
    H.HOUR,
    (COUNT(A.ANIMAL_ID)) AS COUNT
FROM 
    Hours H
LEFT JOIN 
    ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY 
    H.HOUR
ORDER BY 
    H.HOUR;