SELECT 
    U.USER_ID,
    U.NICKNAME,
    SUM(B.PRICE) AS TOTAL_SALES
FROM 
    USED_GOODS_USER U
JOIN 
    USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
WHERE 
    B.STATUS = 'DONE'
GROUP BY 
    U.USER_ID, U.NICKNAME
HAVING 
    SUM(B.PRICE) >= 700000
ORDER BY 
    TOTAL_SALES ASC;

-- 방법 2: 서브쿼리 사용
SELECT 
    U.USER_ID,
    U.NICKNAME,
    T.TOTAL_SALES
FROM 
    USED_GOODS_USER U
JOIN (
    SELECT 
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) T ON U.USER_ID = T.WRITER_ID
ORDER BY 
    T.TOTAL_SALES ASC;