-- 해답: 입양 시각 구하기(1)
SELECT 
    HOUR(DATETIME) AS HOUR,
    COUNT(*) AS COUNT
FROM 
    ANIMAL_OUTS
WHERE 
    HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY 
    HOUR(DATETIME)
ORDER BY 
    HOUR;

-- 방법 2: DATE_FORMAT 사용
SELECT 
    DATE_FORMAT(DATETIME, '%H') AS HOUR,
    COUNT(*) AS COUNT
FROM 
    ANIMAL_OUTS
WHERE 
    DATE_FORMAT(DATETIME, '%H') BETWEEN '09' AND '19'
GROUP BY 
    DATE_FORMAT(DATETIME, '%H')
ORDER BY 
    HOUR;