WITH ReviewCounts AS (
    SELECT MEMBER_ID, COUNT(*) AS review_count
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
TopReviewers AS (
    SELECT MEMBER_ID
    FROM ReviewCounts
    WHERE review_count = (SELECT MAX(review_count) FROM ReviewCounts)
)
SELECT 
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
    REST_REVIEW RR
JOIN 
    TopReviewers TR ON RR.MEMBER_ID = TR.MEMBER_ID
LEFT JOIN 
    MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
ORDER BY 
    RR.REVIEW_DATE, RR.REVIEW_TEXT;