WITH ITEM_RARE AS (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
),
ITEM_PARENT AS (
    SELECT IT.ITEM_ID
    FROM ITEM_TREE IT
    JOIN ITEM_RARE IR ON IT.PARENT_ITEM_ID = IR.ITEM_ID
),
UPGRADED_RARE_ITEMS AS (
    SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
    FROM ITEM_INFO II
    JOIN ITEM_PARENT IP ON II.ITEM_ID = IP.ITEM_ID
)
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM UPGRADED_RARE_ITEMS
ORDER BY ITEM_ID DESC;