WITH ITEM_RARE AS(
    SELECT ITEM_ID
    FROM   ITEM_INFO
    WHERE RARITY = 'RARE'
),
ITEM_PARENT AS(
    SELECT IT.ITEM_ID
    FROM ITEM_TREE IT
    JOIN ITEM_RARE IR ON IT.PARENT_ITEM_ID IN (IR.ITEM_ID)
    
)
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
JOIN  ITEM_PARENT IP ON II.ITEM_ID = IP.ITEM_ID
ORDER BY II.ITEM_ID DESC