SELECT DISTINCT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM 
    DEVELOPERS D
JOIN SKILLCODES SC ON (SC.CODE & D.SKILL_CODE)
WHERE 
    SC.NAME IN ('Python', 'C#')
ORDER BY 
    D.ID ASC;