WITH YearlyMaxSize AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY 
        YEAR(DIFFERENTIATION_DATE)
)
SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    Y.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM 
    ECOLI_DATA E
JOIN 
    YearlyMaxSize Y ON YEAR(E.DIFFERENTIATION_DATE) = Y.YEAR
ORDER BY 
    YEAR(E.DIFFERENTIATION_DATE),
    Y.MAX_SIZE - E.SIZE_OF_COLONY;