WITH SIZE_OF_MAX AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY 
        YEAR(DIFFERENTIATION_DATE)
)
SELECT 
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    SOM.MAX_SIZE - ED.SIZE_OF_COLONY AS YEAR_DEV,
    ED.ID
FROM 
    ECOLI_DATA ED
JOIN 
    SIZE_OF_MAX SOM ON SOM.YEAR = YEAR(ED.DIFFERENTIATION_DATE)
ORDER BY 
    YEAR(ED.DIFFERENTIATION_DATE), YEAR_DEV;