WITH Score_2022 AS (
    SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT 
    s.TOTAL_SCORE AS SCORE,
    e.EMP_NO,
    e.EMP_NAME,
    e.POSITION,
    e.EMAIL
FROM 
    Score_2022 s
JOIN HR_EMPLOYEES e ON s.EMP_NO = e.EMP_NO
WHERE 
    s.TOTAL_SCORE = (SELECT MAX(TOTAL_SCORE) FROM Score_2022)
ORDER BY 
    e.EMP_NO;