-- 해답: 카테고리 별 도서 판매량 집계하기
SELECT 
    B.CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM 
    BOOK B
JOIN 
    BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE 
    S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 
    B.CATEGORY
ORDER BY 
    B.CATEGORY;

-- 방법 2: DATE_FORMAT 사용
SELECT 
    B.CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM 
    BOOK B
JOIN 
    BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE 
    DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY 
    B.CATEGORY
ORDER BY 
    B.CATEGORY;

-- 방법 3: YEAR, MONTH 함수 사용
SELECT 
    B.CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM 
    BOOK B
JOIN 
    BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE 
    YEAR(S.SALES_DATE) = 2022 
    AND MONTH(S.SALES_DATE) = 1
GROUP BY 
    B.CATEGORY
ORDER BY 
    B.CATEGORY;