WITH developer_skills AS (
  SELECT 
    d.ID,
    d.EMAIL,
    CASE
      WHEN (d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0 
        AND (d.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')) > 0 THEN 'A'
      WHEN (d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0 THEN 'B'
      WHEN (d.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')) > 0 THEN 'C'
      ELSE NULL
    END AS GRADE
  FROM 
    DEVELOPERS d
)
SELECT
  GRADE,
  ID,
  EMAIL
FROM 
  developer_skills
WHERE 
  GRADE IS NOT NULL
ORDER BY 
  GRADE, ID;